# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import Engine_pb2 as Engine__pb2


class ServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.LoadFile = channel.unary_unary(
        '/Davidian.engine.Server/LoadFile',
        request_serializer=Engine__pb2.LoadRequest.SerializeToString,
        response_deserializer=Engine__pb2.LoadResponse.FromString,
        )


class ServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def LoadFile(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'LoadFile': grpc.unary_unary_rpc_method_handler(
          servicer.LoadFile,
          request_deserializer=Engine__pb2.LoadRequest.FromString,
          response_serializer=Engine__pb2.LoadResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Davidian.engine.Server', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
