# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Orbital.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Orbital.proto',
  package='Davidian.orbital',
  syntax='proto3',
  serialized_pb=_b('\n\rOrbital.proto\x12\x10\x44\x61vidian.orbital\"\x9f\x01\n\x0fOrbitalElements\x12\x16\n\x0esemimajor_axis\x18\x01 \x01(\x01\x12\x14\n\x0c\x65\x63\x63\x65ntricity\x18\x02 \x01(\x01\x12\x1a\n\x12longitude_asc_node\x18\x03 \x01(\x01\x12\x13\n\x0binclination\x18\x04 \x01(\x01\x12\x15\n\rarg_periapsis\x18\x05 \x01(\x01\x12\x16\n\x0emean_anomaly_0\x18\x06 \x01(\x01\"2\n\x0f\x43\x61rtesianVector\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"w\n\x0bStateVector\x12\x33\n\x08position\x18\x01 \x01(\x0b\x32!.Davidian.orbital.CartesianVector\x12\x33\n\x08velocity\x18\x02 \x01(\x0b\x32!.Davidian.orbital.CartesianVector\"V\n\x08\x42odyData\x12\x18\n\x10parent_body_name\x18\x01 \x01(\t\x12\x30\n\x05orbit\x18\x02 \x01(\x0b\x32!.Davidian.orbital.OrbitalElements\"\x0e\n\x0cRootBodyData\"\xcb\x01\n\x04\x42ody\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04mass\x18\x02 \x01(\x01\x12\x33\n\troot_body\x18\x03 \x01(\x0b\x32\x1e.Davidian.orbital.RootBodyDataH\x00\x12\x34\n\x0e\x63\x65lestial_body\x18\x04 \x01(\x0b\x32\x1a.Davidian.orbital.BodyDataH\x00\x12/\n\tfree_body\x18\x05 \x01(\x0b\x32\x1a.Davidian.orbital.BodyDataH\x00\x42\x0b\n\tbody_datab\x06proto3')
)




_ORBITALELEMENTS = _descriptor.Descriptor(
  name='OrbitalElements',
  full_name='Davidian.orbital.OrbitalElements',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='semimajor_axis', full_name='Davidian.orbital.OrbitalElements.semimajor_axis', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eccentricity', full_name='Davidian.orbital.OrbitalElements.eccentricity', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude_asc_node', full_name='Davidian.orbital.OrbitalElements.longitude_asc_node', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='inclination', full_name='Davidian.orbital.OrbitalElements.inclination', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arg_periapsis', full_name='Davidian.orbital.OrbitalElements.arg_periapsis', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mean_anomaly_0', full_name='Davidian.orbital.OrbitalElements.mean_anomaly_0', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=195,
)


_CARTESIANVECTOR = _descriptor.Descriptor(
  name='CartesianVector',
  full_name='Davidian.orbital.CartesianVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Davidian.orbital.CartesianVector.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='Davidian.orbital.CartesianVector.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='Davidian.orbital.CartesianVector.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=247,
)


_STATEVECTOR = _descriptor.Descriptor(
  name='StateVector',
  full_name='Davidian.orbital.StateVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='Davidian.orbital.StateVector.position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='Davidian.orbital.StateVector.velocity', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=368,
)


_BODYDATA = _descriptor.Descriptor(
  name='BodyData',
  full_name='Davidian.orbital.BodyData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent_body_name', full_name='Davidian.orbital.BodyData.parent_body_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orbit', full_name='Davidian.orbital.BodyData.orbit', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=370,
  serialized_end=456,
)


_ROOTBODYDATA = _descriptor.Descriptor(
  name='RootBodyData',
  full_name='Davidian.orbital.RootBodyData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=458,
  serialized_end=472,
)


_BODY = _descriptor.Descriptor(
  name='Body',
  full_name='Davidian.orbital.Body',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Davidian.orbital.Body.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mass', full_name='Davidian.orbital.Body.mass', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='root_body', full_name='Davidian.orbital.Body.root_body', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='celestial_body', full_name='Davidian.orbital.Body.celestial_body', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='free_body', full_name='Davidian.orbital.Body.free_body', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='body_data', full_name='Davidian.orbital.Body.body_data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=475,
  serialized_end=678,
)

_STATEVECTOR.fields_by_name['position'].message_type = _CARTESIANVECTOR
_STATEVECTOR.fields_by_name['velocity'].message_type = _CARTESIANVECTOR
_BODYDATA.fields_by_name['orbit'].message_type = _ORBITALELEMENTS
_BODY.fields_by_name['root_body'].message_type = _ROOTBODYDATA
_BODY.fields_by_name['celestial_body'].message_type = _BODYDATA
_BODY.fields_by_name['free_body'].message_type = _BODYDATA
_BODY.oneofs_by_name['body_data'].fields.append(
  _BODY.fields_by_name['root_body'])
_BODY.fields_by_name['root_body'].containing_oneof = _BODY.oneofs_by_name['body_data']
_BODY.oneofs_by_name['body_data'].fields.append(
  _BODY.fields_by_name['celestial_body'])
_BODY.fields_by_name['celestial_body'].containing_oneof = _BODY.oneofs_by_name['body_data']
_BODY.oneofs_by_name['body_data'].fields.append(
  _BODY.fields_by_name['free_body'])
_BODY.fields_by_name['free_body'].containing_oneof = _BODY.oneofs_by_name['body_data']
DESCRIPTOR.message_types_by_name['OrbitalElements'] = _ORBITALELEMENTS
DESCRIPTOR.message_types_by_name['CartesianVector'] = _CARTESIANVECTOR
DESCRIPTOR.message_types_by_name['StateVector'] = _STATEVECTOR
DESCRIPTOR.message_types_by_name['BodyData'] = _BODYDATA
DESCRIPTOR.message_types_by_name['RootBodyData'] = _ROOTBODYDATA
DESCRIPTOR.message_types_by_name['Body'] = _BODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OrbitalElements = _reflection.GeneratedProtocolMessageType('OrbitalElements', (_message.Message,), dict(
  DESCRIPTOR = _ORBITALELEMENTS,
  __module__ = 'Orbital_pb2'
  # @@protoc_insertion_point(class_scope:Davidian.orbital.OrbitalElements)
  ))
_sym_db.RegisterMessage(OrbitalElements)

CartesianVector = _reflection.GeneratedProtocolMessageType('CartesianVector', (_message.Message,), dict(
  DESCRIPTOR = _CARTESIANVECTOR,
  __module__ = 'Orbital_pb2'
  # @@protoc_insertion_point(class_scope:Davidian.orbital.CartesianVector)
  ))
_sym_db.RegisterMessage(CartesianVector)

StateVector = _reflection.GeneratedProtocolMessageType('StateVector', (_message.Message,), dict(
  DESCRIPTOR = _STATEVECTOR,
  __module__ = 'Orbital_pb2'
  # @@protoc_insertion_point(class_scope:Davidian.orbital.StateVector)
  ))
_sym_db.RegisterMessage(StateVector)

BodyData = _reflection.GeneratedProtocolMessageType('BodyData', (_message.Message,), dict(
  DESCRIPTOR = _BODYDATA,
  __module__ = 'Orbital_pb2'
  # @@protoc_insertion_point(class_scope:Davidian.orbital.BodyData)
  ))
_sym_db.RegisterMessage(BodyData)

RootBodyData = _reflection.GeneratedProtocolMessageType('RootBodyData', (_message.Message,), dict(
  DESCRIPTOR = _ROOTBODYDATA,
  __module__ = 'Orbital_pb2'
  # @@protoc_insertion_point(class_scope:Davidian.orbital.RootBodyData)
  ))
_sym_db.RegisterMessage(RootBodyData)

Body = _reflection.GeneratedProtocolMessageType('Body', (_message.Message,), dict(
  DESCRIPTOR = _BODY,
  __module__ = 'Orbital_pb2'
  # @@protoc_insertion_point(class_scope:Davidian.orbital.Body)
  ))
_sym_db.RegisterMessage(Body)


# @@protoc_insertion_point(module_scope)
