# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Engine.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Orbital_pb2 as Orbital__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Engine.proto',
  package='Davidian.engine',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x45ngine.proto\x12\x0f\x44\x61vidian.engine\x1a\rOrbital.proto\".\n\x06System\x12$\n\x04\x62ody\x18\x01 \x03(\x0b\x32\x16.Davidian.orbital.Body\"O\n\nOrbitState\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\x33\n\x0cstate_vector\x18\x02 \x01(\x0b\x32\x1d.Davidian.orbital.StateVector\"2\n\x10\x42odyStateRequest\x12\x10\n\x08\x62odyName\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\x01\"k\n\x16\x42odyStateStreamRequest\x12\x10\n\x08\x62odyName\x18\x01 \x01(\t\x12\x12\n\ntime_start\x18\x02 \x01(\x01\x12\x10\n\x08time_end\x18\x03 \x01(\x01\x12\x19\n\x11seconds_per_frame\x18\x04 \x01(\x01\"\x19\n\x17GetCurrentSystemRequest\"W\n\x0bLoadRequest\x12\x12\n\x08\x66ilename\x18\x01 \x01(\tH\x00\x12)\n\x06system\x18\x02 \x01(\x0b\x32\x17.Davidian.engine.SystemH\x00\x42\t\n\x07request2\xdb\x02\n\x06Server\x12\x45\n\nLoadSystem\x12\x1c.Davidian.engine.LoadRequest\x1a\x17.Davidian.engine.System\"\x00\x12W\n\x10GetCurrentSystem\x12(.Davidian.engine.GetCurrentSystemRequest\x1a\x17.Davidian.engine.System\"\x00\x12V\n\x12GetBodyStateAtTime\x12!.Davidian.engine.BodyStateRequest\x1a\x1b.Davidian.engine.OrbitState\"\x00\x12Y\n\rGetBodyStream\x12\'.Davidian.engine.BodyStateStreamRequest\x1a\x1b.Davidian.engine.OrbitState\"\x00\x30\x01\x62\x06proto3')
  ,
  dependencies=[Orbital__pb2.DESCRIPTOR,])




_SYSTEM = _descriptor.Descriptor(
  name='System',
  full_name='Davidian.engine.System',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='Davidian.engine.System.body', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=94,
)


_ORBITSTATE = _descriptor.Descriptor(
  name='OrbitState',
  full_name='Davidian.engine.OrbitState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='Davidian.engine.OrbitState.time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state_vector', full_name='Davidian.engine.OrbitState.state_vector', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=175,
)


_BODYSTATEREQUEST = _descriptor.Descriptor(
  name='BodyStateRequest',
  full_name='Davidian.engine.BodyStateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bodyName', full_name='Davidian.engine.BodyStateRequest.bodyName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='Davidian.engine.BodyStateRequest.time', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=227,
)


_BODYSTATESTREAMREQUEST = _descriptor.Descriptor(
  name='BodyStateStreamRequest',
  full_name='Davidian.engine.BodyStateStreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bodyName', full_name='Davidian.engine.BodyStateStreamRequest.bodyName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_start', full_name='Davidian.engine.BodyStateStreamRequest.time_start', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time_end', full_name='Davidian.engine.BodyStateStreamRequest.time_end', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seconds_per_frame', full_name='Davidian.engine.BodyStateStreamRequest.seconds_per_frame', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=336,
)


_GETCURRENTSYSTEMREQUEST = _descriptor.Descriptor(
  name='GetCurrentSystemRequest',
  full_name='Davidian.engine.GetCurrentSystemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=363,
)


_LOADREQUEST = _descriptor.Descriptor(
  name='LoadRequest',
  full_name='Davidian.engine.LoadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='Davidian.engine.LoadRequest.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='system', full_name='Davidian.engine.LoadRequest.system', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='request', full_name='Davidian.engine.LoadRequest.request',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=365,
  serialized_end=452,
)

_SYSTEM.fields_by_name['body'].message_type = Orbital__pb2._BODY
_ORBITSTATE.fields_by_name['state_vector'].message_type = Orbital__pb2._STATEVECTOR
_LOADREQUEST.fields_by_name['system'].message_type = _SYSTEM
_LOADREQUEST.oneofs_by_name['request'].fields.append(
  _LOADREQUEST.fields_by_name['filename'])
_LOADREQUEST.fields_by_name['filename'].containing_oneof = _LOADREQUEST.oneofs_by_name['request']
_LOADREQUEST.oneofs_by_name['request'].fields.append(
  _LOADREQUEST.fields_by_name['system'])
_LOADREQUEST.fields_by_name['system'].containing_oneof = _LOADREQUEST.oneofs_by_name['request']
DESCRIPTOR.message_types_by_name['System'] = _SYSTEM
DESCRIPTOR.message_types_by_name['OrbitState'] = _ORBITSTATE
DESCRIPTOR.message_types_by_name['BodyStateRequest'] = _BODYSTATEREQUEST
DESCRIPTOR.message_types_by_name['BodyStateStreamRequest'] = _BODYSTATESTREAMREQUEST
DESCRIPTOR.message_types_by_name['GetCurrentSystemRequest'] = _GETCURRENTSYSTEMREQUEST
DESCRIPTOR.message_types_by_name['LoadRequest'] = _LOADREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

System = _reflection.GeneratedProtocolMessageType('System', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEM,
  __module__ = 'Engine_pb2'
  # @@protoc_insertion_point(class_scope:Davidian.engine.System)
  ))
_sym_db.RegisterMessage(System)

OrbitState = _reflection.GeneratedProtocolMessageType('OrbitState', (_message.Message,), dict(
  DESCRIPTOR = _ORBITSTATE,
  __module__ = 'Engine_pb2'
  # @@protoc_insertion_point(class_scope:Davidian.engine.OrbitState)
  ))
_sym_db.RegisterMessage(OrbitState)

BodyStateRequest = _reflection.GeneratedProtocolMessageType('BodyStateRequest', (_message.Message,), dict(
  DESCRIPTOR = _BODYSTATEREQUEST,
  __module__ = 'Engine_pb2'
  # @@protoc_insertion_point(class_scope:Davidian.engine.BodyStateRequest)
  ))
_sym_db.RegisterMessage(BodyStateRequest)

BodyStateStreamRequest = _reflection.GeneratedProtocolMessageType('BodyStateStreamRequest', (_message.Message,), dict(
  DESCRIPTOR = _BODYSTATESTREAMREQUEST,
  __module__ = 'Engine_pb2'
  # @@protoc_insertion_point(class_scope:Davidian.engine.BodyStateStreamRequest)
  ))
_sym_db.RegisterMessage(BodyStateStreamRequest)

GetCurrentSystemRequest = _reflection.GeneratedProtocolMessageType('GetCurrentSystemRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETCURRENTSYSTEMREQUEST,
  __module__ = 'Engine_pb2'
  # @@protoc_insertion_point(class_scope:Davidian.engine.GetCurrentSystemRequest)
  ))
_sym_db.RegisterMessage(GetCurrentSystemRequest)

LoadRequest = _reflection.GeneratedProtocolMessageType('LoadRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOADREQUEST,
  __module__ = 'Engine_pb2'
  # @@protoc_insertion_point(class_scope:Davidian.engine.LoadRequest)
  ))
_sym_db.RegisterMessage(LoadRequest)



_SERVER = _descriptor.ServiceDescriptor(
  name='Server',
  full_name='Davidian.engine.Server',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=455,
  serialized_end=802,
  methods=[
  _descriptor.MethodDescriptor(
    name='LoadSystem',
    full_name='Davidian.engine.Server.LoadSystem',
    index=0,
    containing_service=None,
    input_type=_LOADREQUEST,
    output_type=_SYSTEM,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCurrentSystem',
    full_name='Davidian.engine.Server.GetCurrentSystem',
    index=1,
    containing_service=None,
    input_type=_GETCURRENTSYSTEMREQUEST,
    output_type=_SYSTEM,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBodyStateAtTime',
    full_name='Davidian.engine.Server.GetBodyStateAtTime',
    index=2,
    containing_service=None,
    input_type=_BODYSTATEREQUEST,
    output_type=_ORBITSTATE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetBodyStream',
    full_name='Davidian.engine.Server.GetBodyStream',
    index=3,
    containing_service=None,
    input_type=_BODYSTATESTREAMREQUEST,
    output_type=_ORBITSTATE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER)

DESCRIPTOR.services_by_name['Server'] = _SERVER

# @@protoc_insertion_point(module_scope)
