# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Engine.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from client import Orbital_pb2 as Orbital__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='Engine.proto',
  package='Davidian.engine',
  syntax='proto3',
  serialized_pb=_b('\n\x0c\x45ngine.proto\x12\x0f\x44\x61vidian.engine\x1a\rOrbital.proto\".\n\x06System\x12$\n\x04\x62ody\x18\x01 \x03(\x0b\x32\x16.Davidian.orbital.Body\"O\n\nOrbitState\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\x33\n\x0cstate_vector\x18\x02 \x01(\x0b\x32\x1d.Davidian.orbital.StateVector\"\x1f\n\x0bLoadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"V\n\x0cLoadResponse\x12)\n\x06system\x18\x01 \x01(\x0b\x32\x17.Davidian.engine.SystemH\x00\x12\x0f\n\x05\x65rror\x18\x02 \x01(\tH\x00\x42\n\n\x08response2S\n\x06Server\x12I\n\x08LoadFile\x12\x1c.Davidian.engine.LoadRequest\x1a\x1d.Davidian.engine.LoadResponse\"\x00\x62\x06proto3')
  ,
  dependencies=[Orbital__pb2.DESCRIPTOR,])




_SYSTEM = _descriptor.Descriptor(
  name='System',
  full_name='Davidian.engine.System',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='Davidian.engine.System.body', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=94,
)


_ORBITSTATE = _descriptor.Descriptor(
  name='OrbitState',
  full_name='Davidian.engine.OrbitState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='Davidian.engine.OrbitState.time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state_vector', full_name='Davidian.engine.OrbitState.state_vector', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=175,
)


_LOADREQUEST = _descriptor.Descriptor(
  name='LoadRequest',
  full_name='Davidian.engine.LoadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='Davidian.engine.LoadRequest.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=208,
)


_LOADRESPONSE = _descriptor.Descriptor(
  name='LoadResponse',
  full_name='Davidian.engine.LoadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='system', full_name='Davidian.engine.LoadResponse.system', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='Davidian.engine.LoadResponse.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='Davidian.engine.LoadResponse.response',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=210,
  serialized_end=296,
)

_SYSTEM.fields_by_name['body'].message_type = Orbital__pb2._BODY
_ORBITSTATE.fields_by_name['state_vector'].message_type = Orbital__pb2._STATEVECTOR
_LOADRESPONSE.fields_by_name['system'].message_type = _SYSTEM
_LOADRESPONSE.oneofs_by_name['response'].fields.append(
  _LOADRESPONSE.fields_by_name['system'])
_LOADRESPONSE.fields_by_name['system'].containing_oneof = _LOADRESPONSE.oneofs_by_name['response']
_LOADRESPONSE.oneofs_by_name['response'].fields.append(
  _LOADRESPONSE.fields_by_name['error'])
_LOADRESPONSE.fields_by_name['error'].containing_oneof = _LOADRESPONSE.oneofs_by_name['response']
DESCRIPTOR.message_types_by_name['System'] = _SYSTEM
DESCRIPTOR.message_types_by_name['OrbitState'] = _ORBITSTATE
DESCRIPTOR.message_types_by_name['LoadRequest'] = _LOADREQUEST
DESCRIPTOR.message_types_by_name['LoadResponse'] = _LOADRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

System = _reflection.GeneratedProtocolMessageType('System', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEM,
  __module__ = 'Engine_pb2'
  # @@protoc_insertion_point(class_scope:Davidian.engine.System)
  ))
_sym_db.RegisterMessage(System)

OrbitState = _reflection.GeneratedProtocolMessageType('OrbitState', (_message.Message,), dict(
  DESCRIPTOR = _ORBITSTATE,
  __module__ = 'Engine_pb2'
  # @@protoc_insertion_point(class_scope:Davidian.engine.OrbitState)
  ))
_sym_db.RegisterMessage(OrbitState)

LoadRequest = _reflection.GeneratedProtocolMessageType('LoadRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOADREQUEST,
  __module__ = 'Engine_pb2'
  # @@protoc_insertion_point(class_scope:Davidian.engine.LoadRequest)
  ))
_sym_db.RegisterMessage(LoadRequest)

LoadResponse = _reflection.GeneratedProtocolMessageType('LoadResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOADRESPONSE,
  __module__ = 'Engine_pb2'
  # @@protoc_insertion_point(class_scope:Davidian.engine.LoadResponse)
  ))
_sym_db.RegisterMessage(LoadResponse)



_SERVER = _descriptor.ServiceDescriptor(
  name='Server',
  full_name='Davidian.engine.Server',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=298,
  serialized_end=381,
  methods=[
  _descriptor.MethodDescriptor(
    name='LoadFile',
    full_name='Davidian.engine.Server.LoadFile',
    index=0,
    containing_service=None,
    input_type=_LOADREQUEST,
    output_type=_LOADRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER)

DESCRIPTOR.services_by_name['Server'] = _SERVER

# @@protoc_insertion_point(module_scope)
