# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import Engine_pb2 as Engine__pb2


class ServerStub(object):
  """Service that saves/loads/imports Celestial Systems, and performs calculations for those bodies
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SaveCurrentSystemToFile = channel.unary_unary(
        '/Davidian.engine.Server/SaveCurrentSystemToFile',
        request_serializer=Engine__pb2.SaveCurrentSystemRequest.SerializeToString,
        response_deserializer=Engine__pb2.SaveCurrentSystemResponse.FromString,
        )
    self.LoadSystem = channel.unary_unary(
        '/Davidian.engine.Server/LoadSystem',
        request_serializer=Engine__pb2.LoadRequest.SerializeToString,
        response_deserializer=Engine__pb2.System.FromString,
        )
    self.GetCurrentSystem = channel.unary_unary(
        '/Davidian.engine.Server/GetCurrentSystem',
        request_serializer=Engine__pb2.GetCurrentSystemRequest.SerializeToString,
        response_deserializer=Engine__pb2.System.FromString,
        )
    self.GetBodyStateAtTime = channel.unary_unary(
        '/Davidian.engine.Server/GetBodyStateAtTime',
        request_serializer=Engine__pb2.BodyStateRequest.SerializeToString,
        response_deserializer=Engine__pb2.OrbitState.FromString,
        )
    self.GetBodyStream = channel.unary_stream(
        '/Davidian.engine.Server/GetBodyStream',
        request_serializer=Engine__pb2.BodyStateStreamRequest.SerializeToString,
        response_deserializer=Engine__pb2.OrbitState.FromString,
        )


class ServerServicer(object):
  """Service that saves/loads/imports Celestial Systems, and performs calculations for those bodies
  """

  def SaveCurrentSystemToFile(self, request, context):
    """Save whatever system the service current holds to a named file
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LoadSystem(self, request, context):
    """Import a system from either a direct import, or a named file
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetCurrentSystem(self, request, context):
    """Retrieve the system currently loaded into the service for the client
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBodyStateAtTime(self, request, context):
    """Calculate the state for a specific body at a specific point in time
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetBodyStream(self, request, context):
    """Generate a stream of data for a specific body's state over a length of time
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SaveCurrentSystemToFile': grpc.unary_unary_rpc_method_handler(
          servicer.SaveCurrentSystemToFile,
          request_deserializer=Engine__pb2.SaveCurrentSystemRequest.FromString,
          response_serializer=Engine__pb2.SaveCurrentSystemResponse.SerializeToString,
      ),
      'LoadSystem': grpc.unary_unary_rpc_method_handler(
          servicer.LoadSystem,
          request_deserializer=Engine__pb2.LoadRequest.FromString,
          response_serializer=Engine__pb2.System.SerializeToString,
      ),
      'GetCurrentSystem': grpc.unary_unary_rpc_method_handler(
          servicer.GetCurrentSystem,
          request_deserializer=Engine__pb2.GetCurrentSystemRequest.FromString,
          response_serializer=Engine__pb2.System.SerializeToString,
      ),
      'GetBodyStateAtTime': grpc.unary_unary_rpc_method_handler(
          servicer.GetBodyStateAtTime,
          request_deserializer=Engine__pb2.BodyStateRequest.FromString,
          response_serializer=Engine__pb2.OrbitState.SerializeToString,
      ),
      'GetBodyStream': grpc.unary_stream_rpc_method_handler(
          servicer.GetBodyStream,
          request_deserializer=Engine__pb2.BodyStateStreamRequest.FromString,
          response_serializer=Engine__pb2.OrbitState.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Davidian.engine.Server', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
